### PR TITLE
Added template properties file which states the category for this template

### PR DESCRIPTION
**Pull request by raducoravu**

### CODE REVIEW

**Comment by tgraham-antenna** [comment]
Sorry, but I don't understand what this is for.

**Comment by raducoravu** [comment]
In the same folder with a template file you can have a properties file which specifies various properties of the template file, for example it can specify a custom image icon to be used.
We started the work to integrate your plugin by default in an Oxygen installation.
We have an automated test on our side which states that each template file should have an associated .properties file which should at least state its type. The type of the template may be used for various filters which may be applied on the File->New dialog. For example if I want to create a new DITA resource with a specific "New Topic" action I don't want to see the file templates for creating XSL-FO files.
I added this as a push request in order to have a minimum of modifications between your framework and what will get included in Oxygen.

**Comment by tgraham-antenna** [comment]
Does `XSL-FO.properties` need to be included in the Zip file for the add-on framework?

**Comment by raducoravu** [comment]
Yes Tony, it would be great if you could change the build.xml when you have the time to also include *.properties files from the templates folder.

**Pull request merged**
